### ISSUE TITLE
Binder: install gap-packages

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/demo-semigroup-representation-theory#1]
I would like to install gap_packages in our Dockerfile:

https://github.com/OpenDreamKit/demo-semigroup-representation-theory/blob/292f7a2616cd345c4781a60e4eb152542561700b/Dockerfile#L2-L7

Currently:
- with the non develop base image, `sage -i ...` fails to compile
- with the develop base image: the image builds, but the server fails to start

@embray: ideas?

**Comment by embray** [comment]
Looking into it.  Does it have to be the py3 version?  I don't know what the latest status is on those.
Also, IMO, `sage -i` *should* work on non-develop images, at least following `apt install` of additional build dependencies.  IIRC that's been broken for a while now (I remember having some problem with this back in CIRM) and there is a trac ticket for it.

**Comment by embray** [comment]
This is working now, but it takes a while to launch (see #2).  Also, personally I was having trouble with the RISE slideshow--in particular I had to do so some manual scrolling in order to move through larger slides.  I don't know if that was an issue of my browser, or specific to using RISE in binder (for some reason) or if it's a normal problem you get locally as well...

**Comment by nthiery** [comment]
> Also, personally I was having trouble with the RISE slideshow--in
> particular I had to do so some manual scrolling in order to move
> through larger slides. I don't know if that was an issue of my
> browser, or specific to using RISE in binder (for some reason) or if
> it's a normal problem you get locally as well...

For good or bad the scrolling is on purpose, for slides that did not
have a natural place to break.

Thanks for checking!
